# Prepare

FROM node:8.9.4-alpine

RUN mkdir -p /opt/app

WORKDIR /opt/app

# Install

COPY package.json .
COPY yarn.lock .

RUN yarn

# Run

COPY . /opt/app

ENV NODE_ENV development

ENTRYPOINT ["yarn"]
